language: cpp
jobs:
  include:
    name: cpplint
    script: cpplint --recursive base main node1 node2
    name: build
    script: ./build.sh

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

before_install:
    - pip install --user cpplint
    - eval "${MATRIX_EVAL}"
